export const CREATE_PLAYLIST = "CREATE_PLAYLIST";
export const ADD_TO_PLAYLIST = "ADD_TO_PLAYLIST";
export const REMOVE_FROM_PLAYLIST = "REMOVE_FROM_PLAYLIST";
export const DELETE_PLAYLIST = "DELETE_PLAYLIST";

export const CREATE_TRACK = "CREATE_TRACK";
export const REMOVE_TRACK = "REMOVE_TRACK";