export const UPDATE_PLAYLIST = "UPDATE_PLAYLIST";

export const ADD_TO_CART = "ADD_TO_PLAYLIST";
export const ADD_MULTIPLE_TO_PLAYLIST = "ADD_MULTIPLE_TO_PLAYLIST";
export const REMOVE_FROM_PLAYLIST = "REMOVE_FROM_PLAYLIST";
export const CLEAR_PLAYLIST = "CLEAR_PLAYLIST";
export const TOGGLE_PLAYLIST_CREATE = "TOGGLE_PLAYLIST_CREATE";

export const UPDATE_ARTISTS = "UPDATE_ARTISTS";
export const UPDATE_CURRENT_ARTIST = "UPDATE_CURRENT_ARTIST";